apiVersion: v1
kind: Service
metadata:
  name: student-app-service
spec:
  type: NodePort
  selector:
    app: student-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30002
